#include"EXTI_PRIVATE.h"
#include"EXTI_CONFIG.h"
#include"EXTI_INTERFACE.h"


void EXTI_INIT(){
	//EXTI->EXTI_IMR = 0;
	#if EXTI_LINE == EXTI_LINE_0     &&   EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(0,EXTI->EXTI_IMR);
	SET_BIT(0,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_1  &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(1,EXTI->EXTI_IMR);
	SET_BIT(1,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_2  &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(2,EXTI->EXTI_IMR);
	SET_BIT(2,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_3  &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(3,EXTI->EXTI_IMR);
	SET_BIT(3,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_4  &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(4,EXTI->EXTI_IMR);
	SET_BIT(4,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_5 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(5,EXTI->EXTI_IMR);
	SET_BIT(5,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_6 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(6,EXTI->EXTI_IMR);
	SET_BIT(6,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_7 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(7,EXTI->EXTI_IMR);
	SET_BIT(7,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_8 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(8,EXTI->EXTI_IMR);
	SET_BIT(8,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_9 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(9,EXTI->EXTI_IMR);
	SET_BIT(9,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_10 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(10,EXTI->EXTI_IMR);
	SET_BIT(10,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_11 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(11,EXTI->EXTI_IMR);
	SET_BIT(11,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_12 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(12,EXTI->EXTI_IMR);
	SET_BIT(12,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_13 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(13,EXTI->EXTI_IMR);
	SET_BIT(13,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_14 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(14,EXTI->EXTI_IMR);
	SET_BIT(14,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_15 &&    EXTI_TRIGGER_STATE == EXTI_RAISING_EDGE
	SET_BIT(15,EXTI->EXTI_IMR);
	SET_BIT(15,EXTI->EXTI_RTSR);
	
	#elif EXTI_LINE == EXTI_LINE_0     &&    EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(0,EXTI->EXTI_IMR);
	SET_BIT(0,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_1  &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(1,EXTI->EXTI_IMR);
	SET_BIT(1,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_2  &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(2,EXTI->EXTI_IMR);
	SET_BIT(2,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_3  &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(3,EXTI->EXTI_IMR);
	SET_BIT(3,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_4  &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(4,EXTI->EXTI_IMR);
	SET_BIT(4,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_5 &&      EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(5,EXTI->EXTI_IMR);
	SET_BIT(5,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_6 &&      EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(6,EXTI->EXTI_IMR);
	SET_BIT(6,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_7 &&      EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(7,EXTI->EXTI_IMR);
	SET_BIT(7,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_8 &&      EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(8,EXTI->EXTI_IMR);
	SET_BIT(8,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_9 &&      EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(9,EXTI->EXTI_IMR);
	SET_BIT(9,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_10 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(10,EXTI->EXTI_IMR);
	SET_BIT(10,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_11 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(11,EXTI->EXTI_IMR);
	SET_BIT(11,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_12 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(12,EXTI->EXTI_IMR);
	SET_BIT(12,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_13 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(13,EXTI->EXTI_IMR);
	SET_BIT(13,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_14 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(14,EXTI->EXTI_IMR);
	SET_BIT(14,EXTI->EXTI_FTSR);
	#elif EXTI_LINE == EXTI_LINE_15 &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(15,EXTI->EXTI_IMR);
	SET_BIT(15,EXTI->EXTI_FTSR);
	
	#elif EXTI_LINE == EXTI_LINE_0     &&    EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(0,EXTI->EXTI_IMR);
	SET_BIT(0,EXTI->EXTI_FTSR);
	SET_BIT(0,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_1  &&     EXTI_TRIGGER_STATE == EXTI_FALLING_EDGE
	SET_BIT(1,EXTI->EXTI_IMR);
	SET_BIT(1,EXTI->EXTI_FTSR);
	SET_BIT(1,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_2  &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(2,EXTI->EXTI_IMR);
	SET_BIT(2,EXTI->EXTI_FTSR);
	SET_BIT(2,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_3  &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(3,EXTI->EXTI_IMR);
	SET_BIT(3,EXTI->EXTI_FTSR);
	SET_BIT(3,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_4  &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(4,EXTI->EXTI_IMR);
	SET_BIT(4,EXTI->EXTI_FTSR);
	SET_BIT(4,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_5 &&      EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(5,EXTI->EXTI_IMR);
	SET_BIT(5,EXTI->EXTI_FTSR);
	SET_BIT(5,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_6 &&      EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(6,EXTI->EXTI_IMR);
	SET_BIT(6,EXTI->EXTI_FTSR);
	SET_BIT(6,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_7 &&      EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(7,EXTI->EXTI_IMR);
	SET_BIT(7,EXTI->EXTI_FTSR);
	SET_BIT(7,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_8 &&      EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(8,EXTI->EXTI_IMR);
	SET_BIT(8,EXTI->EXTI_FTSR);
	SET_BIT(8,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_9 &&      EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(9,EXTI->EXTI_IMR);
	SET_BIT(9,EXTI->EXTI_FTSR);
	SET_BIT(9,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_10 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(10,EXTI->EXTI_IMR);
	SET_BIT(10,EXTI->EXTI_FTSR);
	SET_BIT(10,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_11 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(11,EXTI->EXTI_IMR);
	SET_BIT(11,EXTI->EXTI_FTSR);
	SET_BIT(11,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_12 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(12,EXTI->EXTI_IMR);
	SET_BIT(12,EXTI->EXTI_FTSR);
	SET_BIT(12,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_13 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(13,EXTI->EXTI_IMR);
	SET_BIT(13,EXTI->EXTI_FTSR);
	SET_BIT(13,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_14 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(14,EXTI->EXTI_IMR);
	SET_BIT(14,EXTI->EXTI_FTSR);
	SET_BIT(14,EXTI->EXTI_RTSR);
	#elif EXTI_LINE == EXTI_LINE_15 &&     EXTI_TRIGGER_STATE == EXTI_ON_CHANGE
	SET_BIT(15,EXTI->EXTI_IMR);
	SET_BIT(15,EXTI->EXTI_FTSR);
	SET_BIT(15,EXTI->EXTI_RTSR);
	
	
    #endif
    EXTI->EXTI_PR=0xffffffff;
  
}

void EXTI_ENABLE_LINE(u8 Copy_u8Trigger,u8 Copy_u8Line){
	if(Copy_u8Line < 16)
	{
		SET_BIT(Copy_u8Line,EXTI->EXTI_IMR) ;
		switch(Copy_u8Trigger)
		{
		case EXTI_RISING_EDGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			CLR_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			break;
		case EXTI_FALLING_EDGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			CLR_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			break;
		case EXTI_ON_CHANGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			SET_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			break;
		}

	}
}

void EXTI_DISABLE_LINE(u8 Copy_u8Trigger,u8 Copy_u8Line)
{
	if(Copy_u8Line < 16)
	{
		CLR_BIT(Copy_u8Line,EXTI->EXTI_IMR) ;
	}
}

void EXTI_SOFTWARE_TRIGGER(u8 Copy_u8Line){
	if(Copy_u8Line < 16)
	{
		SET_BIT(Copy_u8Line,EXTI->EXTI_SWIER) ;
	}
}

void EXTI_SET_TRIGGER(u8 Copy_u8Trigger,u8 Copy_u8Line){
	if(Copy_u8Line < 16)
	{
		switch(Copy_u8Trigger)
		{
		case EXTI_RISING_EDGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			CLR_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			break;
		case EXTI_FALLING_EDGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			CLR_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			break;
		case EXTI_ON_CHANGE:
			SET_BIT(Copy_u8Line,EXTI->EXTI_RTSR) ;
			SET_BIT(Copy_u8Line,EXTI->EXTI_FTSR) ;
			break;
		}

	}
}