#include"STD_TYPES.h"
#include"BIT_MATH.h"

#include"GPIO_INTERFACE.h"
#include"SPI_PRIVATE.h"
#include"SPI_INTERFACE.h"
#include"SPI_CONFIG.h"

void SPI_INIT(void){
	#if SPI_ENABLE == ENABLE
	SET_BIT(CR1_SPE,SPI->CR1);
	#elif SPI_ENABLE == DISABLE
	CLR_BIT(CR1_SPE,SPI->CR1);
	#endif 
	
	
	#if MASTER_SLAVE_SELECT == SPI_MASTER
	SET_BIT(CR1_MSTR,SPI->CR1);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN7,GPIO_MODE_OUTPUT);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN6,GPIO_MODE_INPUT);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN5,GPIO_MODE_OUTPUT);
	#elif MASTER_SLAVE_SELECT == SPI_SLAVE
	CLR_BIT(CR1_MSTR,SPI->CR1);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN7,GPIO_MODE_INPUT);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN6,GPIO_MODE_OUTPUT);
	GPIO_SET_PIN_MODE(GPIO_PORTA,PIN5,GPIO_MODE_INPUT);
	#endif
	
	#if SPI_DATA_ORDER == SPI_LSB_FIRST
	SET_BIT(CR1_LSBFIRST,SPI->CR1);
	#elif SPI_DATA_ORDER == SPI_MSB_FIRST
	CLR_BIT(CR1_LSBFIRST,SPI->CR1);
	#endif
	
	#if SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_2
	CLR_BIT(CR1_BR0,SPI->CR1);
	CLR_BIT(CR1_BR1,SPI->CR1);
	CLR_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_4
	SET_BIT(CR1_BR0,SPI->CR1);
	CLR_BIT(CR1_BR1,SPI->CR1);
	CLR_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_8
	CLR_BIT(CR1_BR0,SPI->CR1);
	SET_BIT(CR1_BR1,SPI->CR1);
	CLR_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_16
	SET_BIT(CR1_BR0,SPI->CR1);
	SET_BIT(CR1_BR1,SPI->CR1);
	CLR_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_32
	CLR_BIT(CR1_BR0,SPI->CR1);
	CLR_BIT(CR1_BR1,SPI->CR1);
	SET_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_64
	SET_BIT(CR1_BR0,SPI->CR1);
	CLR_BIT(CR1_BR1,SPI->CR1);
	SET_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_128
	CLR_BIT(CR1_BR0,SPI->CR1);
	SET_BIT(CR1_BR1,SPI->CR1);
	SET_BIT(CR1_BR2,SPI->CR1);
	#elif SPI_CLOCK_RATE == SPI_FREQ_DIVIDED_BY_256
	SET_BIT(CR1_BR0,SPI->CR1);
	SET_BIT(CR1_BR1,SPI->CR1);
	SET_BIT(CR1_BR2,SPI->CR1);
	#endif
	
	#if SPI_CLOCK_POLARITY  ==  SPI_RISING_LEADING_FALLING_TRAILING
	CLR_BIT(CR1_CPOL,SPI->CR1);
	#elif SPI_CLOCK_POLARITY  ==  SPI_FALLING_LEADING_RISING_TRAILING
	SET_BIT(CR1_CPOL,SPI->CR1);
	#endif
	
	
	#if RECIEVE_ONLY_MODE   ==   TRANSMIT_RECIEVE
	CLR_BIT(CR1_RXONLY,SPI->CR1);
	#elif RECIEVE_ONLY_MODE   ==   RECIEVE_ONLY
	SET_BIT(CR1_RXONLY,SPI->CR1);
	#endif
	
	
	#if DATA_FRAME_FORMAT     ==    8_BIT_DATA
	CLR_BIT(CR1_DFF,SPI->CR1);
	#elif DATA_FRAME_FORMAT   ==     16_BIT_DATA
	SET_BIT(CR1_DFF,SPI->CR1);
	#endif
	
	
	#if TX_INTERRUPT_ENABLE_STATE   ==   TX_INTERRUPT_ENABLE
	SET_BIT(CR2_TXEIE,SPI->CR2);
	#elif TX_INTERRUPT_ENABLE_STATE   ==   TX_INTERRUPT_DISABLE
	CLR_BIT(CR2_TXEIE,SPI->CR2);
	#endif
	
	
	#if RX_INTERRUPT_ENABLE_STATE   ==   RX_INTERRUPT_ENABLE
	SET_BIT(CR2_RXNE,SPI->CR2);
	#elif RX_INTERRUPT_ENABLE_STATE   ==   RX_INTERRUPT_DISABLE
	CLR_BIT(CR2_RXNE,SPI->CR2);
	#endif
	
	
	#if SOFTWARE_SLAVE_MANAGEMENT   ==   SLAVE_MANAGEMENT_ENABLED
	SET_BIT(CR1_SSI,SPI->CR1);
	SET_BIT(CR1_SSM,SPI->CR1);
	#elif SOFTWARE_SLAVE_MANAGEMENT   ==   SLAVE_MANAGEMENT_DISABLED
	CLR_BIT(CR1_SSI,SPI->CR1);
	CLR_BIT(CR1_SSM,SPI->CR1);
	#endif
	
}
u16   SPI_TRANCIVE(u16 Copy_u16Data){
	SPI -> DR = Copy_u16Data;
	while((GET_BIT(SR_BSY,SPI ->SR)==0));
	return SPI -> DR;
}