#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_


#define TIMEOUT                                            10000UL

/*
SPI_LSB_FIRST
SPI_MSB_FIRST
*/
#define SPI_DATA_ORDER  SPI_LSB_FIRST


/*
SPI_MASTER
SPI_SLAVE 
*/
#define MASTER_SLAVE_SELECT  SPI_MASTER 


/*
SPI_FREQ_DIVIDED_BY_2	
SPI_FREQ_DIVIDED_BY_4	
SPI_FREQ_DIVIDED_BY_8	
SPI_FREQ_DIVIDED_BY_16
SPI_FREQ_DIVIDED_BY_32
SPI_FREQ_DIVIDED_BY_64
SPI_FREQ_DIVIDED_BY_128
*/
#define SPI_CLOCK_RATE  SPI_FREQ_DIVIDED_BY_4


/*
SPI_RISING_LEADING_FALLING_TRAILING
SPI_FALLING_LEADING_RISING_TRAILING
*/   
#define SPI_CLOCK_POLARITY    SPI_RISING_LEADING_FALLING_TRAILING


/*
SPI_SAMPLE_LEADING_SETUP_TRAILING
SPI_SETUP_LEADING_SAMPLE_TRAILING
*/
#define SPI_CLOCK_PHASE     SPI_SAMPLE_LEADING_SETUP_TRAILING


/*
TRANSMIT_RECIEVE
RECIEVE_ONLY    
*/
#define RECIEVE_ONLY_MODE      TRANSMIT_RECIEVE                       ///////////////////////////


/*
8_BIT_DATA 
16_BIT_DATA
*/     
#define DATA_FRAME_FORMAT         8_BIT_DATA


/*
ENABLE
DISABLE
*/
#define SPI_ENABLE                  ENABLE


/*
TX_INTERRUPT_ENABLE 
TX_INTERRUPT_DISABLE
*/
#define TX_INTERRUPT_ENABLE_STATE      TX_INTERRUPT_DISABLE


/*
RX_INTERRUPT_ENABLE 
RX_INTERRUPT_DISABLE
*/
#define RX_INTERRUPT_ENABLE_STATE      RX_INTERRUPT_DISABLE

/*
SLAVE_MANAGEMENT_DISABLED
SLAVE_MANAGEMENT_ENABLED 
*/
#define SOFTWARE_SLAVE_MANAGEMENT      SLAVE_MANAGEMENT_ENABLED

#endif
